### ISSUE TITLE
Failed to open slides on Windows

### ISSUE THREAD

**Issue by divinebovine** [nicoespeon/vscode-slides#1]
## Describe the bug

When activating slide mode, the extension states:
> I failed to open all slides because: Error: ENOENT: no such file or directory, scandir '/c:/dev/presentations/vscode'

## How to reproduce

Use windows, create a folder for a new presentation, add a single markdown file, `01.md`. Activate slide mode.

## Expected behavior

Loads the first markdown file in slide mode.

## Screenshots

![image](https://user-images.githubusercontent.com/2818169/69174697-eda4ed80-0ac7-11ea-837c-571f1562d613.png)

## Additional information

- Version of the extension impacted: 2.0.1

**Comment by nicoespeon** [comment]
Oh thanks, I didn't test the extension on Windows so this might be an OS-specific issue. The folder should have been `presentations/.vscode/` and not `presentations/vscode/`.

Maybe the problem is around here, we're not yet using `path.join()` to build the correct path: https://github.com/nicoespeon/vscode-slides/blob/5032730ee91da3d3990522731df4d8db70e2c960/src/adapters.ts#L101

**Comment by divinebovine** [comment]
Well, my directory structure was misleading. My folder was called vscode... I updated that in this screenshot.

![image](https://user-images.githubusercontent.com/2818169/69192473-438a8d00-0aea-11ea-810d-9d1fca681ac4.png)

**Comment by nicoespeon** [comment]
Hmmm I'm not sure then. I'll try to use `path.join()`, see if it fixes the issue—anyway, I prefer to use this to be OS-agnostic on the path delimiter.

I just deployed a patch so you can test on your end (you should just need to reload VS Code, you can check version is 2.0.2). Can you tell me if it works with the patch?

**Comment by divinebovine** [comment]
I updated, restarted vs code, and I'm still getting the same problem. I'll try debugging the extension and see if I can isolate it.

**Comment by divinebovine** [comment]
Looks like the colon in the `/c:/dev` is what's breaking it.

**Comment by nicoespeon** [comment]
@all-contributors please add divinebovine for bug and code

**Comment by nicoespeon** [comment]
@all-contributors please add divinebovine for bug and code

**Comment by nicoespeon** [comment]
@divinebovine I shipped the fix with v2.0.3. Does it work fine now?

**Comment by divinebovine** [comment]
Yes sir, thank you!
